# Generated by Django 4.2.5 on 2023-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], default='transfer', max_length=20, verbose_name='Метод оплаты'),
        ),
    ]
