# Generated by Django 4.2.5 on 2023-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_payment_currency_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновление'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус подписки'),
        ),
    ]
